# Generated by Django 5.2.4 on 2025-07-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.CharField(null=True),
        ),
    ]
