# Generated by Django 5.1.4 on 2025-07-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.URLField(),
        ),
    ]
