# Generated by Django 5.2.4 on 2025-07-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="product_id",
            field=models.TextField(null=True),
        ),
    ]
